
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 idle_animation.glb 
*/

/* eslint-disable */

import Model from './Idle_animation'
import { Canvas, useFrame } from '@react-three/fiber';



const App = () => {
  return (
    <div style={{height: "1000px"}}>
      <Canvas >
        <Model />
      </Canvas>
    </div>
  );
};

export { App };
