/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/idle_animation.glb 
*/

/* eslint-disable */

import React, { useRef, useLayoutEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/idle_animation.glb')
  const { actions, names } = useAnimations(animations, group);

  useLayoutEffect(() => {
    names.forEach((animation) => {
      actions?.[animation]?.play();
    });
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="root" position={[0, 1, 0]} scale={7}>
          <group name="node_id199" position={[5, 0, 0]} scale={1}>
            <mesh name="mesh_id109" geometry={nodes.mesh_id109.geometry} material={materials['95.001']} position={[27.079, 206.724, 4.253]} rotation={[Math.PI, 0, 0.508]} scale={-1.156} />
            <mesh name="mesh_id115" geometry={nodes.mesh_id115.geometry} material={materials['97.001']} position={[152.928, 42.326, 0.908]} scale={1.327} />
            <mesh name="mesh_id39" geometry={nodes.mesh_id39.geometry} material={materials['87.001']} position={[-11.251, 192.965, 1.671]} rotation={[-0.001, -0.003, -0.001]} scale={[1.268, 1.148, 1.268]} />
            <mesh name="mesh_id41" geometry={nodes.mesh_id41.geometry} material={materials['89.001']} position={[-53.546, 206.71, 4.253]} rotation={[0, 0, 0.508]} scale={1.156} />
            <mesh name="mesh_id49" geometry={nodes.mesh_id49.geometry} material={materials['91.001']} position={[-176.653, 42.326, 0.908]} rotation={[0.009, 0, 0.001]} scale={1.327} />
            <mesh name="mesh_id121" geometry={nodes.mesh_id121.geometry} material={materials['99.001']} position={[46.547, -95.13, 2.23]} scale={1.327} />
            <mesh name="mesh_id37001" geometry={nodes.mesh_id37001.geometry} material={materials['85']} position={[-11.384, 19.005, 1.298]} scale={1.327} />
            <mesh name="mesh_id61" geometry={nodes.mesh_id61.geometry} material={materials['93.001']} position={[-61.827, -95.116, 2.23]} scale={1.327} />
          </group>
        </group> 
      </group>
    </group>
  )
}

useGLTF.preload('/idle_animation.glb')
